package com.ems.license.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * The signed {@code .lic} file artifact imported by the master tenant superadmin.
 * Stores both the raw file content (for re-verification at startup) and the parsed payload.
 *
 * <p>Each import creates a new record; the previous active record is marked SUPERSEDED.
 * Only one record may have {@code importStatus = ACTIVE} at any time, enforced by
 * the partial unique index {@code idx_license_files_active_singleton}.</p>
 *
 * @see LicenseImportStatus
 * @see ApplicationLicenseEntity
 */
@Entity
@Table(name = "license_files")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LicenseFileEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Globally unique license identifier from the payload (e.g., "LIC-2026-0001"). */
    @Column(name = "license_id", nullable = false, unique = true, length = 100)
    private String licenseId;

    /** License format version from the payload (e.g., "1.0"). */
    @Column(name = "format_version", nullable = false, length = 20)
    private String formatVersion;

    /** Key Identifier from the file header. Selects the Ed25519 public key for verification. */
    @Column(name = "kid", nullable = false, length = 100)
    private String kid;

    /** Vendor legal name that generated the license. */
    @Column(name = "issuer", nullable = false)
    private String issuer;

    /** Timestamp when the license file was generated by the vendor. */
    @Column(name = "issued_at", nullable = false)
    private Instant issuedAt;

    /** Customer identifier in vendor CRM. */
    @Column(name = "customer_id", nullable = false, length = 100)
    private String customerId;

    /** Customer legal name. */
    @Column(name = "customer_name", nullable = false)
    private String customerName;

    /** ISO 3166-1 alpha-2 country code (2 characters). */
    @Column(name = "customer_country", length = 2)
    private String customerCountry;

    /** Complete raw {@code .lic} file bytes for re-verification at startup. */
    @Column(name = "raw_content", nullable = false, columnDefinition = "BYTEA")
    private byte[] rawContent;

    /** Decoded JSON payload for querying without re-parsing the binary file. */
    @Column(name = "payload_json", nullable = false, columnDefinition = "TEXT")
    private String payloadJson;

    /** Ed25519 digital signature bytes. */
    @Column(name = "signature", nullable = false, columnDefinition = "BYTEA")
    private byte[] signature;

    /** SHA-256 checksum of the payload (belt-and-suspenders with Ed25519). */
    @Column(name = "payload_checksum", length = 100)
    private String payloadChecksum;

    /** ACTIVE = current license, SUPERSEDED = replaced by newer import. */
    @Enumerated(EnumType.STRING)
    @Column(name = "import_status", nullable = false, length = 20)
    @Builder.Default
    private LicenseImportStatus importStatus = LicenseImportStatus.ACTIVE;

    /** The superadmin user who performed the import (cross-service ref to user-service). */
    @Column(name = "imported_by", nullable = false)
    private UUID importedBy;

    /** Optimistic locking version. */
    @Version
    @Column(name = "version")
    private Long version;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;

    /** The application license extracted from this file (inverse side). */
    @OneToOne(mappedBy = "licenseFile", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private ApplicationLicenseEntity applicationLicense;
}
