global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-facade'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-facade:8081']

  - job_name: 'tenant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tenant-service:8082']

  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:8080']
