-- V4__create_on_premise_licensing_schema.sql
-- Description: Create on-premise cryptographic licensing tables per ADR-015
-- Author: DBA Agent
-- Date: 2026-02-27
-- Source: docs/data-models/CANONICAL-DATA-MODEL.md v2.0 (lines 784-1262)
--
-- This migration creates the complete on-premise licensing schema:
--   1. license_files           - Signed .lic file artifacts imported by superadmin
--   2. application_licenses    - Platform-wide entitlements extracted from license file
--   3. tenant_licenses         - Per-tenant entitlements carved from application license
--   4. tier_seat_allocations   - Seat caps per user tier within a tenant license
--   5. user_license_assignments - Individual user seat assignments (runtime managed)
--   6. revocation_entries      - Revoked license identifiers from .revoke files
--
-- Tables are created in dependency order (parents before children).
-- Cross-service references (tenant_id, user_id) have no database-level FK.

-- ============================================================
-- 1. license_files
-- ============================================================
-- The signed .lic file artifact imported by the master tenant superadmin.
-- Stores both the raw file content (for re-verification) and the parsed payload.
-- Each import creates a new record; the previous active record is marked SUPERSEDED.

CREATE TABLE IF NOT EXISTS license_files (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    license_id          VARCHAR(100)    NOT NULL,
    format_version      VARCHAR(20)     NOT NULL,
    kid                 VARCHAR(100)    NOT NULL,
    issuer              VARCHAR(255)    NOT NULL,
    issued_at           TIMESTAMPTZ     NOT NULL,
    customer_id         VARCHAR(100)    NOT NULL,
    customer_name       VARCHAR(255)    NOT NULL,
    customer_country    VARCHAR(2),
    raw_content         BYTEA           NOT NULL,
    payload_json        TEXT            NOT NULL,
    signature           BYTEA           NOT NULL,
    payload_checksum    VARCHAR(100),
    import_status       VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    imported_by         UUID            NOT NULL,
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Indexes for license_files
CREATE UNIQUE INDEX IF NOT EXISTS idx_license_files_license_id
    ON license_files(license_id);

CREATE INDEX IF NOT EXISTS idx_license_files_import_status
    ON license_files(import_status);

CREATE INDEX IF NOT EXISTS idx_license_files_created_at
    ON license_files(created_at DESC);

-- BR-LF001: Only one ACTIVE license file per installation.
-- Partial unique index ensures at most one row with import_status = 'ACTIVE'.
CREATE UNIQUE INDEX IF NOT EXISTS idx_license_files_active_singleton
    ON license_files(import_status) WHERE import_status = 'ACTIVE';

-- Constraints for license_files
ALTER TABLE license_files ADD CONSTRAINT chk_license_file_import_status
    CHECK (import_status IN ('ACTIVE', 'SUPERSEDED'));

ALTER TABLE license_files ADD CONSTRAINT chk_license_file_customer_country
    CHECK (customer_country IS NULL OR length(customer_country) = 2);

-- Comments for license_files
COMMENT ON TABLE license_files IS 'Signed .lic file artifacts imported by the master tenant superadmin. Each record stores the raw file bytes, parsed payload, and Ed25519 signature for offline re-verification.';
COMMENT ON COLUMN license_files.id IS 'Primary key (UUID)';
COMMENT ON COLUMN license_files.license_id IS 'Globally unique license identifier from payload (e.g., LIC-2026-0001). Used for revocation checking.';
COMMENT ON COLUMN license_files.format_version IS 'License format version from payload (e.g., 1.0)';
COMMENT ON COLUMN license_files.kid IS 'Key Identifier from file header. Selects the Ed25519 public key PEM file for signature verification.';
COMMENT ON COLUMN license_files.issuer IS 'Vendor legal name that generated the license';
COMMENT ON COLUMN license_files.issued_at IS 'Timestamp when the license file was generated by the vendor';
COMMENT ON COLUMN license_files.customer_id IS 'Customer identifier in vendor CRM';
COMMENT ON COLUMN license_files.customer_name IS 'Customer legal name';
COMMENT ON COLUMN license_files.customer_country IS 'ISO 3166-1 alpha-2 country code (2 characters)';
COMMENT ON COLUMN license_files.raw_content IS 'Complete raw .lic file bytes for re-verification at startup';
COMMENT ON COLUMN license_files.payload_json IS 'Decoded JSON payload for querying without re-parsing the binary file';
COMMENT ON COLUMN license_files.signature IS 'Ed25519 digital signature bytes';
COMMENT ON COLUMN license_files.payload_checksum IS 'SHA-256 checksum of the payload (belt-and-suspenders with Ed25519)';
COMMENT ON COLUMN license_files.import_status IS 'ACTIVE = current license, SUPERSEDED = replaced by newer import';
COMMENT ON COLUMN license_files.imported_by IS 'Superadmin user who performed the import (cross-service ref to user-service)';
COMMENT ON COLUMN license_files.version IS 'Optimistic locking version for JPA @Version';
COMMENT ON COLUMN license_files.created_at IS 'Import timestamp';
COMMENT ON COLUMN license_files.updated_at IS 'Last update timestamp';


-- ============================================================
-- 2. application_licenses
-- ============================================================
-- Top-level entitlement extracted from the license file payload.
-- Exactly one per active license file. Defines platform-wide constraints:
-- product version range, max tenants, expiry, master feature set, and grace period.

CREATE TABLE IF NOT EXISTS application_licenses (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    license_file_id     UUID            NOT NULL,
    product             VARCHAR(100)    NOT NULL,
    version_min         VARCHAR(20)     NOT NULL,
    version_max         VARCHAR(20)     NOT NULL,
    instance_id         VARCHAR(255),
    max_tenants         INTEGER         NOT NULL,
    expires_at          TIMESTAMPTZ     NOT NULL,
    features            JSONB           NOT NULL,
    grace_period_days   INTEGER         NOT NULL DEFAULT 30,
    degraded_features   JSONB           NOT NULL DEFAULT '[]',
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Indexes for application_licenses
CREATE UNIQUE INDEX IF NOT EXISTS idx_application_licenses_license_file
    ON application_licenses(license_file_id);

CREATE INDEX IF NOT EXISTS idx_application_licenses_expires_at
    ON application_licenses(expires_at);

CREATE INDEX IF NOT EXISTS idx_application_licenses_product
    ON application_licenses(product);

-- Foreign key: application_licenses -> license_files (1:1, CASCADE on delete)
ALTER TABLE application_licenses ADD CONSTRAINT fk_application_licenses_file
    FOREIGN KEY (license_file_id) REFERENCES license_files(id) ON DELETE CASCADE;

-- Constraints for application_licenses
ALTER TABLE application_licenses ADD CONSTRAINT chk_app_license_max_tenants
    CHECK (max_tenants > 0);

ALTER TABLE application_licenses ADD CONSTRAINT chk_app_license_grace_period
    CHECK (grace_period_days >= 0);

-- Comments for application_licenses
COMMENT ON TABLE application_licenses IS 'Platform-wide entitlement extracted from the signed license file. One per active license file. Defines max tenants, feature ceiling, version range, and grace period.';
COMMENT ON COLUMN application_licenses.id IS 'Primary key (UUID)';
COMMENT ON COLUMN application_licenses.license_file_id IS 'FK to the license file this entitlement was extracted from (1:1)';
COMMENT ON COLUMN application_licenses.product IS 'Product identifier (must match EMSIST)';
COMMENT ON COLUMN application_licenses.version_min IS 'Minimum application version (semver, e.g., 1.0.0)';
COMMENT ON COLUMN application_licenses.version_max IS 'Maximum application version (semver, e.g., 2.99.99)';
COMMENT ON COLUMN application_licenses.instance_id IS 'Optional hardware/instance binding identifier';
COMMENT ON COLUMN application_licenses.max_tenants IS 'Maximum number of tenants permitted by this license';
COMMENT ON COLUMN application_licenses.expires_at IS 'Application-level license expiry date';
COMMENT ON COLUMN application_licenses.features IS 'Master feature set as JSONB array (e.g., ["basic_workflows","advanced_reports"])';
COMMENT ON COLUMN application_licenses.grace_period_days IS 'Days of degraded operation after expiry (default 30, BR-AL008)';
COMMENT ON COLUMN application_licenses.degraded_features IS 'Features disabled during grace period as JSONB array';
COMMENT ON COLUMN application_licenses.version IS 'Optimistic locking version for JPA @Version';
COMMENT ON COLUMN application_licenses.created_at IS 'Creation timestamp';
COMMENT ON COLUMN application_licenses.updated_at IS 'Last update timestamp';


-- ============================================================
-- 3. tenant_licenses
-- ============================================================
-- Per-tenant entitlement carved from the application license.
-- Each licensed tenant has one tenant license record per active license file.
-- tenant_id is a cross-service reference to tenant-service (no DB-level FK).

CREATE TABLE IF NOT EXISTS tenant_licenses (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    application_license_id  UUID            NOT NULL,
    tenant_id               VARCHAR(50)     NOT NULL,
    display_name            VARCHAR(255)    NOT NULL,
    expires_at              TIMESTAMPTZ     NOT NULL,
    features                JSONB           NOT NULL,
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Indexes for tenant_licenses
-- Composite unique: one tenant license per application license per tenant
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_licenses_app_tenant
    ON tenant_licenses(application_license_id, tenant_id);

CREATE INDEX IF NOT EXISTS idx_tenant_licenses_tenant_id
    ON tenant_licenses(tenant_id);

CREATE INDEX IF NOT EXISTS idx_tenant_licenses_expires_at
    ON tenant_licenses(expires_at);

-- Foreign key: tenant_licenses -> application_licenses (N:1, CASCADE on delete)
ALTER TABLE tenant_licenses ADD CONSTRAINT fk_tenant_licenses_app_license
    FOREIGN KEY (application_license_id) REFERENCES application_licenses(id) ON DELETE CASCADE;

-- Comments for tenant_licenses
COMMENT ON TABLE tenant_licenses IS 'Per-tenant entitlement carved from the application license. Specifies which features are enabled and the tenant-specific expiry date.';
COMMENT ON COLUMN tenant_licenses.id IS 'Primary key (UUID)';
COMMENT ON COLUMN tenant_licenses.application_license_id IS 'FK to the parent application license';
COMMENT ON COLUMN tenant_licenses.tenant_id IS 'Tenant identifier (cross-service ref to tenant-service, no DB FK)';
COMMENT ON COLUMN tenant_licenses.display_name IS 'Human-readable tenant name from the license file';
COMMENT ON COLUMN tenant_licenses.expires_at IS 'Tenant-specific expiry date (must be <= application expiry, enforced at app level)';
COMMENT ON COLUMN tenant_licenses.features IS 'Features enabled for this tenant as JSONB array (subset of application features)';
COMMENT ON COLUMN tenant_licenses.version IS 'Optimistic locking version for JPA @Version';
COMMENT ON COLUMN tenant_licenses.created_at IS 'Creation timestamp';
COMMENT ON COLUMN tenant_licenses.updated_at IS 'Last update timestamp';


-- ============================================================
-- 4. tier_seat_allocations
-- ============================================================
-- Maximum seats per user tier within a tenant license.
-- Each tenant license has exactly 4 records (one per UserTier value).

CREATE TABLE IF NOT EXISTS tier_seat_allocations (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_license_id   UUID            NOT NULL,
    tier                VARCHAR(20)     NOT NULL,
    max_seats           INTEGER         NOT NULL,
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Indexes for tier_seat_allocations
-- BR-TSA001: Composite unique -- one allocation per tier per tenant license
CREATE UNIQUE INDEX IF NOT EXISTS idx_tier_seat_allocations_license_tier
    ON tier_seat_allocations(tenant_license_id, tier);

CREATE INDEX IF NOT EXISTS idx_tier_seat_allocations_tenant_license
    ON tier_seat_allocations(tenant_license_id);

-- Foreign key: tier_seat_allocations -> tenant_licenses (N:1, CASCADE on delete)
ALTER TABLE tier_seat_allocations ADD CONSTRAINT fk_tier_seat_allocations_tenant_license
    FOREIGN KEY (tenant_license_id) REFERENCES tenant_licenses(id) ON DELETE CASCADE;

-- Constraints for tier_seat_allocations
-- Only valid UserTier enum values
ALTER TABLE tier_seat_allocations ADD CONSTRAINT chk_tier_seat_tier
    CHECK (tier IN ('TENANT_ADMIN', 'POWER_USER', 'CONTRIBUTOR', 'VIEWER'));

-- BR-TSA003/BR-TSA004: -1 = unlimited, otherwise must be non-negative
ALTER TABLE tier_seat_allocations ADD CONSTRAINT chk_tier_seat_max_seats
    CHECK (max_seats = -1 OR max_seats >= 0);

-- Comments for tier_seat_allocations
COMMENT ON TABLE tier_seat_allocations IS 'Maximum seats per user tier within a tenant license. Each tenant license has exactly 4 records (TENANT_ADMIN, POWER_USER, CONTRIBUTOR, VIEWER).';
COMMENT ON COLUMN tier_seat_allocations.id IS 'Primary key (UUID)';
COMMENT ON COLUMN tier_seat_allocations.tenant_license_id IS 'FK to the parent tenant license';
COMMENT ON COLUMN tier_seat_allocations.tier IS 'User tier: TENANT_ADMIN, POWER_USER, CONTRIBUTOR, VIEWER';
COMMENT ON COLUMN tier_seat_allocations.max_seats IS 'Maximum seats for this tier. -1 means unlimited.';
COMMENT ON COLUMN tier_seat_allocations.version IS 'Optimistic locking version for JPA @Version';
COMMENT ON COLUMN tier_seat_allocations.created_at IS 'Creation timestamp';
COMMENT ON COLUMN tier_seat_allocations.updated_at IS 'Last update timestamp';


-- ============================================================
-- 5. user_license_assignments
-- ============================================================
-- Individual user seat assignments within a tenant.
-- This is the only licensing entity actively managed at runtime.
-- user_id and tenant_id are cross-service references (no DB-level FK).

CREATE TABLE IF NOT EXISTS user_license_assignments (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_license_id   UUID            NOT NULL,
    user_id             UUID            NOT NULL,
    tenant_id           VARCHAR(50)     NOT NULL,
    tier                VARCHAR(20)     NOT NULL,
    assigned_at         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    assigned_by         UUID            NOT NULL,
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Indexes for user_license_assignments
-- BR-ULA001: One tier per tenant per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_license_assignments_user_tenant
    ON user_license_assignments(user_id, tenant_id);

CREATE INDEX IF NOT EXISTS idx_user_license_assignments_tenant_license
    ON user_license_assignments(tenant_license_id);

CREATE INDEX IF NOT EXISTS idx_user_license_assignments_tenant_id
    ON user_license_assignments(tenant_id);

-- Composite index for seat count queries: "how many users of tier X in tenant Y?"
CREATE INDEX IF NOT EXISTS idx_user_license_assignments_tier
    ON user_license_assignments(tenant_id, tier);

-- Foreign key: user_license_assignments -> tenant_licenses (N:1, CASCADE on delete)
ALTER TABLE user_license_assignments ADD CONSTRAINT fk_user_license_assignments_tenant_license
    FOREIGN KEY (tenant_license_id) REFERENCES tenant_licenses(id) ON DELETE CASCADE;

-- Constraints for user_license_assignments
ALTER TABLE user_license_assignments ADD CONSTRAINT chk_user_license_tier
    CHECK (tier IN ('TENANT_ADMIN', 'POWER_USER', 'CONTRIBUTOR', 'VIEWER'));

-- Comments for user_license_assignments
COMMENT ON TABLE user_license_assignments IS 'Individual user seat assignments within a tenant. The only licensing entity managed at runtime (all others are imported from the license file). Each user holds at most one seat tier per tenant.';
COMMENT ON COLUMN user_license_assignments.id IS 'Primary key (UUID)';
COMMENT ON COLUMN user_license_assignments.tenant_license_id IS 'FK to the parent tenant license';
COMMENT ON COLUMN user_license_assignments.user_id IS 'User holding this seat (cross-service ref to user-service, no DB FK)';
COMMENT ON COLUMN user_license_assignments.tenant_id IS 'Tenant context (denormalized from tenant_license for query efficiency, cross-service ref)';
COMMENT ON COLUMN user_license_assignments.tier IS 'Assigned capability tier: TENANT_ADMIN, POWER_USER, CONTRIBUTOR, VIEWER';
COMMENT ON COLUMN user_license_assignments.assigned_at IS 'When the seat was allocated';
COMMENT ON COLUMN user_license_assignments.assigned_by IS 'Administrator who allocated the seat (cross-service ref to user-service)';
COMMENT ON COLUMN user_license_assignments.version IS 'Optimistic locking version for JPA @Version';
COMMENT ON COLUMN user_license_assignments.created_at IS 'Creation timestamp';
COMMENT ON COLUMN user_license_assignments.updated_at IS 'Last update timestamp';


-- ============================================================
-- 6. revocation_entries
-- ============================================================
-- Record of revoked license identifiers from .revoke files.
-- Allows the vendor to invalidate specific licenses without internet.
-- Entries are immutable: INSERT only, no UPDATE or DELETE.

CREATE TABLE IF NOT EXISTS revocation_entries (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    revoked_license_id  VARCHAR(100)    NOT NULL,
    revocation_reason   TEXT,
    revoked_at          TIMESTAMPTZ     NOT NULL,
    imported_at         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Indexes for revocation_entries
-- Unique: each license ID can only be revoked once
CREATE UNIQUE INDEX IF NOT EXISTS idx_revocation_entries_license_id
    ON revocation_entries(revoked_license_id);

CREATE INDEX IF NOT EXISTS idx_revocation_entries_imported_at
    ON revocation_entries(imported_at DESC);

-- Comments for revocation_entries
COMMENT ON TABLE revocation_entries IS 'Record of revoked license identifiers imported from .revoke files. Entries are immutable (INSERT only). Allows offline license invalidation without internet connectivity.';
COMMENT ON COLUMN revocation_entries.id IS 'Primary key (UUID)';
COMMENT ON COLUMN revocation_entries.revoked_license_id IS 'The license identifier that is no longer valid (matches license_files.license_id)';
COMMENT ON COLUMN revocation_entries.revocation_reason IS 'Human-readable reason for revocation';
COMMENT ON COLUMN revocation_entries.revoked_at IS 'When the revocation was issued by the vendor';
COMMENT ON COLUMN revocation_entries.imported_at IS 'When this entry was imported into the system';
COMMENT ON COLUMN revocation_entries.created_at IS 'Creation timestamp';
