/**
 * Legacy PrimeIcon name -> Phosphor Thin icon name mapping.
 *
 * Keys are the PrimeIcon names (without 'pi pi-' prefix).
 * Values are the Phosphor Thin icon names as exported by @ng-icons/phosphor-icons/thin.
 *
 * Source: docs/lld/icon-migration-lld.md Section 8.
 */
export const ICON_NAME_MAP: Record<string, string> = {
  // ── iconOptions array (78 icons from master-definitions-section) ──────────
  box: 'phosphorCubeThin',
  server: 'phosphorDesktopThin',
  database: 'phosphorDatabaseThin',
  desktop: 'phosphorMonitorThin',
  mobile: 'phosphorDeviceMobileThin',
  cloud: 'phosphorCloudThin',
  cog: 'phosphorGearThin',
  wrench: 'phosphorWrenchThin',
  bolt: 'phosphorLightningThin',
  shield: 'phosphorShieldThin',
  user: 'phosphorUserThin',
  users: 'phosphorUsersThin',
  home: 'phosphorHouseThin',
  'chart-bar': 'phosphorChartBarThin',
  'chart-line': 'phosphorChartLineThin',
  'chart-pie': 'phosphorChartPieThin',
  file: 'phosphorFileThin',
  folder: 'phosphorFolderThin',
  envelope: 'phosphorEnvelopeThin',
  calendar: 'phosphorCalendarThin',
  clock: 'phosphorClockThin',
  tag: 'phosphorTagThin',
  bookmark: 'phosphorBookmarkSimpleThin',
  star: 'phosphorStarThin',
  heart: 'phosphorHeartThin',
  flag: 'phosphorFlagThin',
  globe: 'phosphorGlobeThin',
  link: 'phosphorLinkThin',
  lock: 'phosphorLockThin',
  sitemap: 'phosphorTreeStructureThin',
  'th-large': 'phosphorSquaresFourThin',
  list: 'phosphorListThin',
  'align-justify': 'phosphorTextAlignJustifyThin',
  'sliders-h': 'phosphorSlidersThin',
  inbox: 'phosphorTrayThin',
  send: 'phosphorPaperPlaneTiltThin',
  'map-marker': 'phosphorMapPinThin',
  microchip: 'phosphorCpuThin',
  wifi: 'phosphorWifiHighThin',
  key: 'phosphorKeyThin',
  'id-card': 'phosphorIdentificationCardThin',
  warehouse: 'phosphorWarehouseThin',
  truck: 'phosphorTruckThin',
  'money-bill': 'phosphorMoneyThin',
  'shopping-cart': 'phosphorShoppingCartThin',
  comments: 'phosphorChatCircleThin',
  phone: 'phosphorPhoneThin',
  print: 'phosphorPrinterThin',
  search: 'phosphorMagnifyingGlassThin',
  eye: 'phosphorEyeThin',
  pencil: 'phosphorPencilSimpleThin',
  'check-circle': 'phosphorCheckCircleThin',
  'exclamation-triangle': 'phosphorWarningThin',
  'info-circle': 'phosphorInfoThin',
  'question-circle': 'phosphorQuestionThin',
  image: 'phosphorImageThin',
  video: 'phosphorVideoCameraThin',
  headphones: 'phosphorHeadphonesThin',
  map: 'phosphorMapTrifoldThin',
  directions: 'phosphorSignpostThin',
  hammer: 'phosphorHammerThin',
  clipboard: 'phosphorClipboardThin',
  megaphone: 'phosphorMegaphoneThin',
  stopwatch: 'phosphorTimerThin',
  palette: 'phosphorPaletteThin',
  code: 'phosphorCodeThin',
  copy: 'phosphorCopyThin',
  filter: 'phosphorFunnelThin',
  'sort-alt': 'phosphorSortAscendingThin',
  'arrows-alt': 'phosphorArrowsOutCardinalThin',
  'share-alt': 'phosphorShareNetworkThin',
  eraser: 'phosphorEraserThin',
  receipt: 'phosphorReceiptThin',
  briefcase: 'phosphorBriefcaseThin',
  'building-columns': 'phosphorBuildingsThin',
  'graduation-cap': 'phosphorGraduationCapThin',
  'wave-pulse': 'phosphorWaveSineThin',

  // ── Additional PrimeIcons from templates (Section 8.2) ────────────────────
  refresh: 'phosphorArrowClockwiseThin',
  times: 'phosphorXThin',
  plus: 'phosphorPlusThin',
  trash: 'phosphorTrashThin',
  'chevron-left': 'phosphorCaretLeftThin',
  'chevron-right': 'phosphorCaretRightThin',
  'chevron-down': 'phosphorCaretDownThin',
  bars: 'phosphorListThin',
  play: 'phosphorPlayThin',
  sync: 'phosphorArrowsClockwiseThin',
  check: 'phosphorCheckThin',
  undo: 'phosphorArrowCounterClockwiseThin',

  // ── Component catalog extras (Section 8.3) ────────────────────────────────
  'sort-numeric-up': 'phosphorSortAscendingThin',
  'check-square': 'phosphorCheckSquareThin',
  hashtag: 'phosphorHashThin',
  table: 'phosphorTableThin',
  'ellipsis-h': 'phosphorDotsThreeOutlineThin',
  'arrow-right-arrow-left': 'phosphorArrowsLeftRightThin',
  clone: 'phosphorCopySimpleThin',
  'window-maximize': 'phosphorFrameCornersThin',
  minus: 'phosphorMinusThin',
  'arrow-down': 'phosphorArrowDownThin',
  circle: 'phosphorCircleThin',
  'power-off': 'phosphorPowerThin',
  compass: 'phosphorCompassThin',
  'arrow-right': 'phosphorArrowRightThin',
  comment: 'phosphorChatCircleThin',
  bell: 'phosphorBellThin',
  'circle-fill': 'phosphorCircleThin',
  'align-left': 'phosphorTextAlignLeftThin',
  'ellipsis-v': 'phosphorDotsThreeVerticalThin',
  images: 'phosphorImagesThin',
  spinner: 'phosphorSpinnerThin',
  percentage: 'phosphorPercentThin',
  'arrow-up': 'phosphorArrowUpThin',
  ban: 'phosphorProhibitThin',
  'eye-slash': 'phosphorEyeSlashThin',
  unlock: 'phosphorLockOpenThin',
  download: 'phosphorDownloadThin',
  upload: 'phosphorUploadThin',
  save: 'phosphorFloppyDiskThin',
  redo: 'phosphorArrowClockwiseThin',
  'exclamation-circle': 'phosphorWarningCircleThin',
  'times-circle': 'phosphorXCircleThin',
  'arrow-left': 'phosphorArrowLeftThin',
  'chevron-up': 'phosphorCaretUpThin',
  'angle-double-left': 'phosphorCaretDoubleLeftThin',
  'angle-double-right': 'phosphorCaretDoubleRightThin',
  'list-ul': 'phosphorListBulletsThin',
  sort: 'phosphorSortAscendingThin',
  'sort-amount-down': 'phosphorSortDescendingThin',
  building: 'phosphorBuildingsThin',
  'sign-in': 'phosphorSignInThin',
  'sign-out': 'phosphorSignOutThin',
  tags: 'phosphorTagThin',
  'thumbs-up': 'phosphorThumbsUpThin',
  'thumbs-down': 'phosphorThumbsDownThin',
};

/** Default fallback icon when a name cannot be resolved. */
export const DEFAULT_ICON = 'phosphorCubeThin';
