import { EnvironmentProviders, makeEnvironmentProviders } from '@angular/core';
import { provideIcons, provideNgIconsConfig, provideNgIconLoader } from '@ng-icons/core';

// ── Phosphor Thin icon imports (tree-shakeable) ─────────────────────────────
// Only icons actually referenced in the ICON_NAME_MAP and ICON_CATEGORIES
// are imported here, keeping the bundle minimal.
import {
  phosphorCubeThin,
  phosphorDesktopThin,
  phosphorDatabaseThin,
  phosphorMonitorThin,
  phosphorDeviceMobileThin,
  phosphorCloudThin,
  phosphorGearThin,
  phosphorWrenchThin,
  phosphorLightningThin,
  phosphorShieldThin,
  phosphorUserThin,
  phosphorUsersThin,
  phosphorHouseThin,
  phosphorChartBarThin,
  phosphorChartLineThin,
  phosphorChartPieThin,
  phosphorFileThin,
  phosphorFolderThin,
  phosphorEnvelopeThin,
  phosphorCalendarThin,
  phosphorClockThin,
  phosphorTagThin,
  phosphorBookmarkSimpleThin,
  phosphorStarThin,
  phosphorHeartThin,
  phosphorFlagThin,
  phosphorGlobeThin,
  phosphorLinkThin,
  phosphorLockThin,
  phosphorTreeStructureThin,
  phosphorSquaresFourThin,
  phosphorListThin,
  phosphorTextAlignJustifyThin,
  phosphorSlidersThin,
  phosphorTrayThin,
  phosphorPaperPlaneTiltThin,
  phosphorMapPinThin,
  phosphorCpuThin,
  phosphorWifiHighThin,
  phosphorKeyThin,
  phosphorIdentificationCardThin,
  phosphorWarehouseThin,
  phosphorTruckThin,
  phosphorMoneyThin,
  phosphorShoppingCartThin,
  phosphorChatCircleThin,
  phosphorPhoneThin,
  phosphorPrinterThin,
  phosphorMagnifyingGlassThin,
  phosphorEyeThin,
  phosphorPencilSimpleThin,
  phosphorCheckCircleThin,
  phosphorPauseCircleThin,
  phosphorPlayCircleThin,
  phosphorWarningThin,
  phosphorInfoThin,
  phosphorQuestionThin,
  phosphorImageThin,
  phosphorVideoCameraThin,
  phosphorHeadphonesThin,
  phosphorMapTrifoldThin,
  phosphorSignpostThin,
  phosphorHammerThin,
  phosphorClipboardThin,
  phosphorMegaphoneThin,
  phosphorTimerThin,
  phosphorPaletteThin,
  phosphorCodeThin,
  phosphorCopyThin,
  phosphorFunnelThin,
  phosphorSortAscendingThin,
  phosphorArrowsOutCardinalThin,
  phosphorShareNetworkThin,
  phosphorEraserThin,
  phosphorReceiptThin,
  phosphorBriefcaseThin,
  phosphorBuildingsThin,
  phosphorGraduationCapThin,
  phosphorWaveSineThin,
  // Template-only icons
  phosphorArrowClockwiseThin,
  phosphorXThin,
  phosphorPlusThin,
  phosphorTrashThin,
  phosphorPauseThin,
  phosphorCaretLeftThin,
  phosphorCaretRightThin,
  phosphorCaretDownThin,
  phosphorPlayThin,
  phosphorArrowsClockwiseThin,
  phosphorArrowsDownUpThin,
  phosphorArrowsOutThin,
  phosphorCheckThin,
  phosphorArrowCounterClockwiseThin,
  // Catalog extras
  phosphorCheckSquareThin,
  phosphorHashThin,
  phosphorTableThin,
  phosphorChatThin,
  phosphorDesktopTowerThin,
  phosphorDotsThreeThin,
  phosphorDotsThreeOutlineThin,
  phosphorArrowsLeftRightThin,
  phosphorCopySimpleThin,
  phosphorFrameCornersThin,
  phosphorMinusThin,
  phosphorArrowDownThin,
  phosphorCircleThin,
  phosphorPowerThin,
  phosphorCompassThin,
  phosphorArrowRightThin,
  phosphorBellThin,
  phosphorTextAlignLeftThin,
  phosphorDotsThreeVerticalThin,
  phosphorImagesThin,
  phosphorSpinnerThin,
  phosphorPercentThin,
  phosphorArrowUpThin,
  phosphorProhibitThin,
  phosphorEyeSlashThin,
  phosphorLockOpenThin,
  phosphorDownloadThin,
  phosphorUploadThin,
  phosphorFloppyDiskThin,
  phosphorWarningCircleThin,
  phosphorXCircleThin,
  phosphorArrowLeftThin,
  phosphorCaretUpThin,
  phosphorCaretDoubleLeftThin,
  phosphorCaretDoubleRightThin,
  phosphorListBulletsThin,
  phosphorSortDescendingThin,
  phosphorSignInThin,
  phosphorSignOutThin,
  phosphorThumbsUpThin,
  phosphorThumbsDownThin,
} from '@ng-icons/phosphor-icons/thin';

/**
 * Provide all icon-related configuration for the application.
 *
 * Call this in app.config.ts providers array:
 * ```ts
 * providers: [
 *   provideAppIcons(),
 *   // ...other providers
 * ]
 * ```
 */
export function provideAppIcons(): EnvironmentProviders {
  return makeEnvironmentProviders([
    provideNgIconsConfig({ size: '20' }),
    provideIcons({
      // General
      phosphorCubeThin,
      phosphorHouseThin,
      phosphorGearThin,
      phosphorWrenchThin,
      phosphorLightningThin,
      phosphorShieldThin,
      phosphorStarThin,
      phosphorHeartThin,
      phosphorFlagThin,
      phosphorBookmarkSimpleThin,
      phosphorTagThin,
      phosphorBellThin,
      phosphorLockThin,
      phosphorLockOpenThin,
      phosphorKeyThin,
      phosphorEyeThin,
      phosphorEyeSlashThin,
      phosphorMagnifyingGlassThin,
      phosphorPencilSimpleThin,
      phosphorTrashThin,
      phosphorCopyThin,
      phosphorClipboardThin,
      phosphorFloppyDiskThin,
      phosphorPrinterThin,
      phosphorDownloadThin,
      phosphorUploadThin,
      phosphorSpinnerThin,
      phosphorPlusThin,
      phosphorMinusThin,
      phosphorXThin,
      phosphorCheckThin,
      phosphorSlidersThin,
      phosphorFunnelThin,
      phosphorPowerThin,
      phosphorPaletteThin,
      phosphorCodeThin,
      phosphorHammerThin,
      phosphorEraserThin,
      // Navigation
      phosphorArrowLeftThin,
      phosphorArrowRightThin,
      phosphorArrowUpThin,
      phosphorArrowDownThin,
      phosphorCaretLeftThin,
      phosphorCaretRightThin,
      phosphorCaretUpThin,
      phosphorCaretDownThin,
      phosphorCaretDoubleLeftThin,
      phosphorCaretDoubleRightThin,
      phosphorArrowClockwiseThin,
      phosphorArrowCounterClockwiseThin,
      phosphorArrowsClockwiseThin,
      phosphorArrowsDownUpThin,
      phosphorArrowsOutThin,
      phosphorArrowsOutCardinalThin,
      phosphorArrowsLeftRightThin,
      phosphorSignInThin,
      phosphorSignOutThin,
      phosphorShareNetworkThin,
      phosphorPlayThin,
      phosphorPauseThin,
      // Data & Charts
      phosphorChartBarThin,
      phosphorChartLineThin,
      phosphorChartPieThin,
      phosphorDatabaseThin,
      phosphorTableThin,
      phosphorListThin,
      phosphorListBulletsThin,
      phosphorSquaresFourThin,
      phosphorSortAscendingThin,
      phosphorSortDescendingThin,
      phosphorTreeStructureThin,
      phosphorPercentThin,
      phosphorHashThin,
      phosphorCheckSquareThin,
      // Communication
      phosphorEnvelopeThin,
      phosphorPhoneThin,
      phosphorChatThin,
      phosphorChatCircleThin,
      phosphorMegaphoneThin,
      phosphorPaperPlaneTiltThin,
      phosphorGlobeThin,
      phosphorLinkThin,
      // Files & Media
      phosphorFileThin,
      phosphorFolderThin,
      phosphorImageThin,
      phosphorImagesThin,
      phosphorVideoCameraThin,
      phosphorHeadphonesThin,
      phosphorReceiptThin,
      // Status & Alerts
      phosphorCheckCircleThin,
      phosphorPauseCircleThin,
      phosphorPlayCircleThin,
      phosphorWarningThin,
      phosphorWarningCircleThin,
      phosphorInfoThin,
      phosphorQuestionThin,
      phosphorXCircleThin,
      phosphorProhibitThin,
      phosphorCircleThin,
      // Commerce & Business
      phosphorBriefcaseThin,
      phosphorBuildingsThin,
      phosphorMoneyThin,
      phosphorShoppingCartThin,
      phosphorGraduationCapThin,
      phosphorWarehouseThin,
      phosphorTruckThin,
      phosphorIdentificationCardThin,
      // Devices & Infrastructure
      phosphorDesktopThin,
      phosphorDesktopTowerThin,
      phosphorMonitorThin,
      phosphorDeviceMobileThin,
      phosphorCloudThin,
      phosphorCpuThin,
      phosphorWifiHighThin,
      // Location & Time
      phosphorMapPinThin,
      phosphorMapTrifoldThin,
      phosphorSignpostThin,
      phosphorCompassThin,
      phosphorCalendarThin,
      phosphorClockThin,
      phosphorTimerThin,
      phosphorTrayThin,
      // Layout & Text
      phosphorTextAlignJustifyThin,
      phosphorTextAlignLeftThin,
      phosphorDotsThreeThin,
      phosphorDotsThreeOutlineThin,
      phosphorDotsThreeVerticalThin,
      phosphorFrameCornersThin,
      phosphorCopySimpleThin,
      phosphorWaveSineThin,
      phosphorThumbsUpThin,
      phosphorThumbsDownThin,
      // User
      phosphorUserThin,
      phosphorUsersThin,
    }),
    // Custom BPMN icon loader -- fetches SVG from /assets/icons/bpmn/
    provideNgIconLoader((name) => {
      if (name.startsWith('bpmn')) {
        return fetch(`/assets/icons/bpmn/${name}.svg`).then((res) => {
          if (!res.ok) {
            console.warn(`[IconLoader] Failed to load BPMN icon: ${name}`);
            return '';
          }
          return res.text();
        });
      }
      return undefined as unknown as string;
    }),
  ]);
}
